### ISSUE TITLE
What all the funcations available with your plugin?

### ISSUE THREAD

**Issue by pandu-49-zz** [artesaos/laravel-linkedin#7]
Please provide us a wiki page that describes about all available functions to use.

**Comment by mauri870** [comment]
This project is a wrapper for the https://github.com/Happyr/LinkedIn-API-client
The methods available are the same as the package above.
The unique difference is how you call the methods.
Instead of `new Happyr\LinkedIn\LinkedIn('app_id', 'app_secret');` you can call Linkedin::methodname.

The laravel container will inject the credentials from the config file and return a fresh instance for you
